title: ParanoiaSystem
description: ParanoiaSystem Marco Ferraioli personal website and blog
keywords: ParanoiaSystem, Marco Ferraioli, blog, personal website, personal blog, programming, software development, software engineering

url: https://paranoiasystem.com
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
header: large

sass:
  style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
- title: Home
  url: /index.html
- title: About Me
  url: /about

social:
  github: paranoiasystem
  email: marcoferraioli@live.com
  linkedin: marcoferraioli93

google_analytics: "G-7X8B5HW3JY"

disqus:
  shortname: paranoiasystem
